[build]
  command = "npm run build"
  publish = "dist"

# Rimuove l'intestazione Content-Security-Policy di Netlify per evitare conflitti con 'eval'
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = ""

# Gestione redirect per React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
